apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: greet-with-new-component
  title: Greeting with new component
  description: Greeting workflow
  annotations:
    orchestrator.io/workflows: '[]'
    sonataflow.org/description: YAML based greeting workflow
    sonataflow.org/expressionLang: jq
    sonataflow.org/profile: gitops
    sonataflow.org/version: "1.0"
  tags:
    - orchestrator
spec:
  type: service
  dependsOn:
    - component: default/red-hat-developer-hub

  parameters:
    - title: Provide workflow inputs
      required:
        - language
      properties:
        language:
          title: Language
          type: string
          ui:autofocus: true
          enum:
            - 'English'
            - 'Spanish'
          default: 'English'
        name:
          title: Name
          type: string
          pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'

  steps:
    - id: register
      name: Register in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

    - id: runWorkflow
      name: Run workflow
      action: orchestrator:workflow:run
      input:
        workflow_id: yamlgreet
        targetEntity: component:default/example-component
        parameters: # matches workflow's dataInputSchema
          language: ${{ parameters.language }}
          name: ${{ parameters.name }}

  output:
    links:
      - title: View in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
      - title: Open workflow run
        url: ${{ steps.runWorkflow.output.instanceUrl }}
